version: '3'
services:
  cv:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - cv:/build/output.html

  worker:
    depends_on:
      - cv
    image: nginx:1.23.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./configs/worker.conf:/etc/nginx/conf.d/default.conf
      - cv:/usr/share/nginx/html

volumes:
  cv: