stages:
  - build
  - test
  - deploy

build app:
  stage: build
  tags:
    - practice
  script:
    - docker build . -t gitlabci-practice

test app:
  stage: test
  tags:
    - practice
  script:
    - docker run --rm gitlabci-practice /app/test.sh

deploy app:
  stage: deploy
  tags:
    - practice
  when: manual
  script:
    - docker stop deployed-container && docker rm deployed-container
    - docker run -d --name=deployed-container gitlab-practice /app/run.sh