name: Build
on:
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: false
          tags: user:app/latest
