name: Image CI

on:
  push:
    branches: [ "main" ]
  pull-request:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        file: ./module3-docker/Dockerfile
        push: false
        tags: user/app:${{ env.TAG }}